import { ProgressIndicator } from "std-widgets.slint";
export component DownloadDialog inherits Dialog {
    width: 320px;
    height: 160px;
    title: @tr("Download Progress");

    in-out property <float> download-progress: 0.0; 
    in-out property <string> download-status: @tr("Preparing to download...");

    VerticalLayout {
        padding: 25px;
        spacing: 15px;
        alignment: center;
        
        Text {
            text: root.download-status;
            font-size: 14px;
            horizontal-alignment: center;
        }
        
        ProgressIndicator {
            progress: root.download-progress;
        }
    }
}