import { AppTheme } from "@theme";
import { AppData } from "@global";
export component Footer inherits Rectangle {
    in property <string> version: "v0.0.1";
    background: #111111;
    preferred-height: 20px;
    max-height: 20px;
    vertical-stretch: 0;
    border-color: AppTheme.colors.sidebar-border;
    border-width: 1px;
    HorizontalLayout {
        width: 100%;
        height: 100%;
        padding-left: 10px;
        padding-right: 10px;
        spacing: 10px;
        HorizontalLayout {
            horizontal-stretch: 1;
            spacing: 6px;
            Rectangle {
                width: 8px; height: 8px; border-radius: 4px;
                y: (parent.height - self.height) / 2;
                background: AppData.network-checking
                    ? #999999
                    : (AppData.is-online ? #76bc51 : #e74c3c);
            }
            Text {
                text: AppData.network-checking
                    ? @tr("Status: Connecting")
                    : (AppData.is-online ? @tr("Status: Online") : @tr("Status: Offline"));
                vertical-alignment: center;
                font-size: 12px;
                color: AppData.network-checking
                    ? #999999
                    : (AppData.is-online ? #76bc51 : #e74c3c);
            }
        }

        Text {
            text: @tr("© 2026 Derrick. All rights reserved.");
            horizontal-alignment: center;
            vertical-alignment: center;
            horizontal-stretch: 1;
            font-size: 12px;
            color: #9e9e9e;
        }

        Text {
            text: root.version;
            vertical-alignment: center;
            horizontal-alignment: right;
            horizontal-stretch: 1;
            font-size: 12px;
            color: gray;
        }
    }
}
