import { AppTheme } from "@theme";
export component Footer inherits Rectangle {
    in property <string> version: "v0.0.1";
    background: #111111;
    preferred-height: 20px;
    max-height: 20px;
    vertical-stretch: 0;
    border-color: AppTheme.colors.sidebar-border;
    border-width: 1px;
    HorizontalLayout {
        width: 100%;
        height: 100%;
        padding-left: 10px;
        padding-right: 10px;
        spacing: 10px;
        Text {
            text: "Status: Connecting";
            vertical-alignment: center;
            font-size: 12px;
            color: green;
        }

        Text {
            text: "© 2026 Derrick. All rights reserved.";
            horizontal-alignment: center;
            vertical-alignment: center;
            horizontal-stretch: 1;
        }

        Text {
            text: root.version;
            vertical-alignment: center;
            font-size: 12px;
            color: gray;
        }
    }
}
