import { AppTheme } from "@theme";
import { Button } from "std-widgets.slint";
import { PageAccountLogic } from "@global";
import { AccountTable, AccountRow } from "account-table.slint";

export component Account inherits Rectangle {
    width: 100%;
    height: 100%;
    background: AppTheme.colors.background;

    VerticalLayout {
        padding: 12px;
        spacing: 8px;

        Text {
            text: @tr("Account Management");
            color: AppTheme.colors.foreground;
            font-size: AppTheme.h2;
            font-weight: AppTheme.font-weight-medium;
        }

        HorizontalLayout {
            vertical-stretch: 1;
            spacing: 8px;

            AccountTable {
                horizontal-stretch: 1;
                rows: [
                    { checked: true, username: "derrick921213", status: @tr("Ready") },
                ];
                selected-index <=> PageAccountLogic.selected-index;
            }

            VerticalLayout {
                spacing: 10px;
                alignment: start;

                Button {
                    text: @tr("Add Microsoft Account");
                    clicked => PageAccountLogic.login_with_microsoft();
                }
                Button {
                    text: @tr("Add Offline Account");
                    clicked => PageAccountLogic.add-offline-account();
                }
                Button {
                    enabled: PageAccountLogic.selected-index >= 0;
                    text: @tr("Refresh");
                    clicked => PageAccountLogic.refresh-account();
                }
                Button {
                    enabled: PageAccountLogic.selected-index >= 0;
                    text: @tr("Remove");
                    clicked => PageAccountLogic.remove-account();
                }
                Button {
                    enabled: PageAccountLogic.selected-index >= 0;
                    text: @tr("Set as Default Account");
                    clicked => PageAccountLogic.set-default-account();
                }
                Button {
                    text: @tr("Unset Default Account");
                    clicked => PageAccountLogic.unset-default-account();
                }

                Rectangle {
                    height: 1px;
                    background: AppTheme.colors.border;
                }

                Button {
                    text: @tr("Manage Appearance");
                    clicked => PageAccountLogic.manage-appearance();
                }
            }
        }

        HorizontalLayout {
            spacing: 8px;

            Button {
                text: @tr("Help");
            }
            Rectangle { horizontal-stretch: 1; }
            Button {
                text: @tr("Cancel");
                clicked => PageAccountLogic.cancel_login();
            }
            Button {
                text: @tr("Confirm");
            }
        }
    }
}
