import { SideTabId } from "@global";
import { AppTheme } from "@theme";
import { Home } from "home.slint";
import { Instances } from "instances.slint";
import { Account } from "account.slint";
import { Mods } from "mods.slint";
export component Pages inherits Rectangle {
    in property <SideTabId> active-tab;
    property <bool> is-wip: //active-tab == SideTabId.mods 
                     active-tab == SideTabId.downloads
                    //  || active-tab == SideTabId.account
                     || active-tab == SideTabId.settings;
    background: AppTheme.colors.background;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    if active-tab == SideTabId.home: Home {}
    if active-tab == SideTabId.instances: Instances {}
    if active-tab == SideTabId.account: Account {}
    if active-tab == SideTabId.mods: Mods {}
    if root.is-wip: Rectangle {
        Text {
            text: @tr("WIP ...");
            font-size: 30px;
            font-weight: 700;
            color: AppTheme.colors.foreground;
        }
    }
}
