import { AppTheme } from "@theme";
import { Assets } from "@assets";

component AddInstance inherits Rectangle {
    in property <string> text;
    in property <image> icon;
    in property <bool> is_primary: true;
    callback clicked;

    background: ta.pressed ? (is_primary ? #5a9e3f : #454545) : (ta.has-hover ? (is_primary ? #76bc51 : #3d3d3d) : (is_primary ? #67ab44 : #333333));
    border-radius: 8px;
    height: 36px;
    width: layout.preferred-width + 24px;

    ta := TouchArea {
        clicked => {
            root.clicked()
        }
    }

    layout := HorizontalLayout {
        spacing: 8px;
        padding-left: 12px;
        padding-right: 12px;
        padding-top: 8px;
        padding-bottom: 8px;
        alignment: center;
        if (root.icon.width > 0): Image {
            width: 20px;
            height: 100%;
            image-fit: contain;
            vertical-alignment: center;
            horizontal-alignment: center;
            source: root.icon;
            colorize: white;
        }
        Text {
            text: root.text;
            color: white;
            font-size: 16px;
            font-weight: 700;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}

component Search inherits Rectangle {
    // background: red;
    height: 100%;
    border-radius: AppTheme.radius-lg;
    border-color: #ffffff.with-alpha(0.6);
    border-width: 1px;
    in-out property <string> search-text <=> ti.text;
    callback _clear-focus();
    _clear-focus => {
        ti.clear-focus();
    }
    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 10px;
        s-i := Rectangle {
            width: 24px;
            height: 100%;
            Image {
                source: Assets.search;
                width: 20px;
                height: 20px;
                vertical-alignment: center;
                horizontal-alignment: center;
                image-fit: contain;
            }
        }

        Rectangle {
            horizontal-stretch: 1;
            if (!ti.has-focus && ti.text == ""): Text {
                text: @tr("Search instances...");
                color: white.with-alpha(0.5);
                vertical-alignment: center;
                horizontal-alignment: left;
                font-size: 16px;
                width: 100%;
            }

            ti := TextInput {
                width: 100%;
                height: 100%;
                color: white;
                font-size: 16px;
                vertical-alignment: center;
                accepted => {
                    root._clear-focus();
                }
            }
        }
    }
}

export component Instances inherits Rectangle {
    background: AppTheme.colors.background;
    callback new_instance();
    TouchArea {
        clicked => {
            s-c._clear-focus();
        }
    }

    VerticalLayout {
        Rectangle {
            VerticalLayout {
                padding-top: 20px;
                padding-left: 10px;
                padding-right: 10px;
                padding-bottom: 20px;
                spacing: 10px;
                height: 140px;
                VerticalLayout {
                    height: 50px;
                    HorizontalLayout {
                        alignment: space-between;
                        height: 50px;
                        Rectangle {
                            width: 40px;
                            height: 40px;
                            Image {
                                source: Assets.cube;
                                width: 100%;
                                height: 100%;
                                image-fit: contain;
                            }
                        }

                        Text {
                            text: @tr("My Instances");
                            font-size: 30px;
                            font-weight: 700;
                            color: AppTheme.colors.foreground;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }

                        AddInstance {
                            text: @tr("Create");
                            icon: Assets.plus;
                            clicked => root.new_instance();
                        }
                    }
                }

                VerticalLayout {
                    height: 50px;
                    s-c := Search { }
                }
            }
        }

        Text {
            text: @tr("Instances Page");
            font-size: 20px;
            color: AppTheme.colors.foreground;
        }

        Rectangle { }
    }
}
