import { Button, VerticalBox } from "std-widgets.slint";

export component MyButton {
    width: 200px;
    height: 60px;
    in property <string> label: "Button";
    callback clicked();
    Rectangle {
        background: #93c0c9;
        Text {
            text: label;
            font-size: 30px;
        }

        TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
}

export component MyApp {
    property <int> count: 0;
    width: 300px;
    height: 300px;
    MyButton {
        label: "Hello! " + count;
        clicked => {
            count = count + 1;
        }
    }
}
