import { SideBar, Footer, SideTabId, Pages } from "components/index.slint";
import { Assets } from "@assets";
import { AppTheme } from "@theme";
import { AppData,InstanceLogic } from "@global";

export { AppData, InstanceLogic }
export component MainApp inherits Window {
    min-width: 800px;
    min-height: 600px;
    preferred-width: 800px;
    preferred-height: 600px;
    title: "VoxelRuler";
    icon: Assets.logo;

    // property <SideTabId> active-tab <=> sidebar.active-tab;
    callback sidebar_change(SideTabId);

    sidebar_change(id) => {
        debug(id)
    }

    VerticalLayout {
        spacing: 0;
        app := HorizontalLayout {
            vertical-stretch: 1;
            sidebar := SideBar {
                tab-changed(id) => root.sidebar_change(id);
            }

            pages := Pages {
                active-tab: sidebar.active-tab;
            }
        }

        footer := Footer {
            vertical-stretch: 0;
            version: AppData.version;
        }
    }
}
