export global Assets {
    out property <image> logo: @image-url("icons/voxelruler.png");
    out property <image> home: @image-url("icons/Home.svg");
    out property <image> download: @image-url("icons/Download.svg");
    out property <image> folder: @image-url("icons/Folder.svg");
    out property <image> plus: @image-url("icons/Plus.svg");
    out property <image> search: @image-url("icons/Search.svg");
    out property <image> setting: @image-url("icons/Setting.svg");
    out property <image> user: @image-url("icons/User.svg");
    out property <image> window: @image-url("icons/Window.svg");
}